PROCESSOR P16F887
INCLUDE <P16F887.INC>

__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)

ENT		EQU		0x20
NA		EQU		0x21
NB		EQU		0x22
RESU	EQU		0x23
XA		EQU		0x24
XB		EQU		0x25

		ORG		0x00
		
		BANKSEL	ANSEL
		CLRF	ANSEL
		CLRF	ANSELH
		
		BANKSEL	TRISA
		MOVLW	0xFF
		MOVWF	TRISA
		CLRF	TRISB
		MOVLW	0x0F
		MOVWF	TRISC
		CLRF	TRISD
		CLRF	TRISE

		BANKSEL	PORTA
		CLRF	NA
		CLRF	NB
 	
C_P		MOVF	PORTA,W
		ANDLW	0x0F
		MOVWF	NB
		MOVF	PORTA,W
		ANDLW	0xF0
		MOVWF	NA
		SWAPF	NA,F
		CLRF	RESU

		MOVF	PORTC,W
		ANDLW	0x03
		MOVWF	ENT
		SUBLW	0x00
		BTFSC	STATUS,Z
		GOTO	SUM
		MOVF	ENT,W
		SUBLW	0x01
		BTFSC	STATUS,Z
		GOTO 	SUB
		GOTO	C_MORD

SUM		MOVF	NA,W
		ADDWF	NB,W	
		MOVWF	RESU
		GOTO	S_R
	
SUB		MOVF	NA,W	
		SUBWF	NB,W
		MOVWF	RESU
		GOTO	S_R

C_MORD	MOVF	NA,F
		BTFSC	STATUS,Z
		GOTO 	S_R
		MOVF	NB,F
		BTFSC	STATUS,Z
		GOTO 	S_R
		
		MOVF	ENT,W
		SUBLW	0x02
		BTFSC	STATUS,Z		
		GOTO	MULT
		MOVF	ENT,W
		SUBLW	0x03
		BTFSC	STATUS,Z		
		GOTO	DIV
		GOTO 	S_R
				
MULT 	MOVF	NA,W
		SUBWF	NB,W
		BTFSC	STATUS,C	
		GOTO	AM
		MOVF	NB,W
		MOVWF	XB
		MOVF	NA,W
		MOVWF	XA
		GOTO 	DOITM

AM		MOVF	NA,W
		MOVWF	XB
		MOVF	NB,W
		MOVWF	XA

DOITM	MOVF 	XB,W
		ADDWF	RESU,F
		DECFSZ	XA,F
		GOTO	DOITM
		GOTO 	S_R
		
DIV		MOVF	NA,W
		SUBWF	NB,F
		BTFSS	STATUS, C
		GOTO	S_R
		INCF	RESU,F
		GOTO	DIV

S_R		MOVF	RESU,W
		MOVWF	PORTB		
		GOTO	C_P

		END
	